---
lab_files:
  - { file: ansible.cfg,        directory: "" } 
  - { file: ssh.cfg,            directory: ssh/ } 
  - { file: ssh-jumpbox.cfg,    directory: ssh/  } 
  - { file: docker_aliases.env, directory: utilities/ } 
...
