---

ENVY_USER_OUTPUT: ENVY_USER_OUTPUT

envy_name:                    multi
envy_state:                   present

envy_pre_run_message:         ""
envy_post_run_message:        ""

envy_local_user:              "{{ lookup('env', 'USER') }}"
envy_local_home:              "{{ lookup('env', 'HOME') }}"

envy_default_image:          vmlet-rhel8-ansible

envy_ssh_user:                devops
envy_ssh_private_key_file:    provision_key.pem
envy_ssh_public_key_file:     provision_key.pub

envy_default_domain:          example.com

envy_networks:
  - name:                     "{{ envy_default_domain }}"
  - name:                     internal.com

envy_labels:
  env_name:                   multi
  created_by:                 envy
  guid:                       "{{ env | default('000000') }}"

...
