---

envy_name:                    rhel8

envy_networks:
  - name:                     "{{ envy_default_domain | default('example.com') }}"

envy_instances:

  - name: rhel8
    group: rhel8
    image: vmlet-rhel8-ansible
    volumes:
      - "{{ envy_local_home }}/shared_dir/:/home/{{ envy_ssh_user }}/shared_dir:z,rw"
      - "{{ envy_local_home }}/repos/:/repos/:z,rw"

...
