---

- name: Create env directory structure
  file:
    path:     "{{ env_home_directory | default('~') }}/{{ __directory }}"
    state:    directory
    mode:     0755
  loop: "{{ envy_directories }}"
  loop_control:
    loop_var: __directory

- name: Generate lab static inventory file
  template:
    src:      lab_inventory.j2
    dest:     "env-{{ env_name }}/inventory"
    mode:     0755

- name: Copy ssh key to lab/ssh default to vagrant
  copy:
    src:      "{{ env_ssh_private_key | default('vagrant.private') }}"
    dest:     "env-{{ env_name }}/ssh/{{ env_ssh_private_key | default('vagrant.private') }}"
    mode:     0400

- name: Write ansible lab config files
  template:
    src:     "{{ __files.file }}.j2"
    dest:    "env-{{ env_name }}/{{ __files.directory }}/{{ __files.file }}"
    mode:     0755
  loop:     "{{ envy_files }}"
  loop_control:
    loop_var: __files

- name: Create user ssh Include cofig file
  template:
    src:     ssh.cfg.j2
    dest:    ~/.ssh/envy-config
    mode:     0755
...
