---
- repo: https://github.com/adrienverge/yamllint.git
  sha: v1.25.0
  hooks:
    - id: yamllint

#- repo: https://github.com/ansible/ansible-lint.git
#  sha: v4.3.7
#  hooks:
#  - id: ansible-lint
#    files: \.(yaml|yml)$
...
