namespace: tonykay
name: envy
version: 0.0.1
readme: README.md

authors:
  - Tony Kay tok@redhat.com

description: EnvY Environments in YAML

license:
  - GPL-2.0-or-later

tags:
  - containers
  - docker

dependencies:
  - docker.community: "*"

repository: https://github.com/tonykay/tonykay.envy
documentation: http://docs.example.com
homepage: http://example.com
issues: https://github.com/tonykay/tonykay.envy/issues
