---

- name: Setup pre-requisite python3 packages
  package:
    name: "{{ yum_dependencies_python3 }}"
    state: present

- name: Setup pre-requisite pip3 packages
  pip:
    name: "{{ pip_dependencies }}"
    state: present
    executable: /usr/bin/pip3

- name: Copy requirements.txt to target for virtualenv
  copy:
    src: requirements_python3.txt
    dest: /tmp/requirements.txt
    mode: 0644

- name: "Create virtualenv {{ virtual_env_name }} for Envy"
  pip:
    virtualenv: "{{ virtual_env_home }}/{{ virtual_env_name }}"
    virtualenv_command: /usr/local/bin/virtualenv
    virtualenv_python: /usr/bin/python3
    virtualenv_site_packages: no
    requirements: /tmp/requirements.txt

...
