---

- name: Red Hat Setup for Docker based host
  when: ansible_os_family == 'RedHat'
  include_tasks: redhat_distro_docker_host_setup.yml

- name: "Install nv command to {{ envy_setup_nv_command_home }}"
  copy:
    src:      nv
    dest:     "{{ envy_setup_nv_command_home | default('/usr/local/bin') }}/nv"
    owner:    root
    mode:     0555
  become: true
  #  become: "{{ 'false' if ansible_system == 'Darwin' else 'true' }}"

...
