---

- name: Red Hat Setup for Docker based host
  when: ansible_os_family == 'RedHat'
  include_tasks: redhat_distro_docker_host_setup.yml

- name: "Install nv command to {{ envy_setup_nv_command_home }}"
  file:
    src:      nv
    path:     "{{ envy_setup_nv_command_home | default('/usr/local/bin') }}"
    state:   present
    mode:     0555

...
