#!/bin/bash

# Setup vars

VIRTUALENV_HOME=/opt/envy/venv-envy
NUM_ARGS=$#
ACTION=$1
OBJECT=$2
TARGET=$3

usage ()
{
  echo "USAGE: nv <action> <object> <extras>"
  echo
  echo "nv deploy environment                  Deploy an Environment"
  echo "nv destroy environment                 Destroy an Environment"
  echo "nv fromfile <filename>                 Deploy an Environemnts from file"
  echo "nv list                                List running instances"
  echo "nv redeploy <environment>              Destroy and Redeploy an environmnet"
  echo "nv replace <environment>  <target>     Destroy and Redeploy an environmnet"
  echo "nv setup                               Reconfigure nv"
  return
}

process_cmd_line ()
{
  if [ $NUM_ARGS -eq 0 ]; 
  then
    usage
    exit 2
  fi
}  

setup_nv_parameters ()
{
  TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")        # For logfile identification
}

activate_virtualenv ()
{
  if [ -f "$VIRTUALENV_HOME"/bin/activate ];
  then
    source /opt/envy/venv-envy/bin/activate
  fi
}

cmd_list ()
{
  echo
  docker network list --format "table {{.Name}}" | egrep -v "^bridge$|^host$|^none$" | sed 's/^NAME$/DOMAINS/'
  echo
  docker ps --format "table {{.Names}}\\t{{.Image}}\\t{{.Status}}" | sed 's/IMAGE   /INSTANCE/'
  echo
}

cmd_default ()
{
ansible-playbook \
  ~/.ansible/collections/ansible_collections/tonykay/envy/playbooks/"${1}".yml \
  -e "envy=${2}" # -e @${ENVY_PATH}/playbooks/vars/addons/"${3}".yml
}

cmd_add ()
{
ansible-playbook \
  ~/.ansible/collections/ansible_collections/tonykay/envy/playbooks/"${1}".yml \
  -e "envy=${2}" -e @~/.ansible/collections/ansible_collections/tonykay/envy/playbooks/vars/addons/"${3}".yml
}

cmd_setup ()
{
   ansible-playbook ~/.ansible/collections/ansible_collections/tonykay/envy/playbooks/setup.yml
}

cmd_update ()     # Update envy and other dependencies
{
   ansible-galaxy install -r ~/.ansible/collections/requirements.yml --force-with-deps
}  

cmd_fromfile ()     # Update envy and other dependencies
{
   ansible-playbook ~/.ansible/collections/ansible_collections/tonykay/envy/playbooks/deploy.yml -e @"$OBJECT"
}  

cmd_replace ()     # Replace an instance
{
  ansible-playbook \
  ~/.ansible/collections/ansible_collections/tonykay/envy/playbooks/replace.yml \
  -e "envy=${OBJECT}" -e  "envy_replacement_target=${TARGET}"

}  
cmd_login ()     # Update envy and other dependencies
{
  docker exec -it $1 bash
}  
process_cmd_line
setup_nv_parameters
activate_virtualenv

# cd  ~/.ansible/collections/ansible_collections/tonykay/envy/playbooks

case "$ACTION" in
  add)
    cmd_add deploy $2 $3
    ;;
  deploy | destroy | redeploy)
    cmd_default $1 $2
    ;;
  fromfile)
    cmd_fromfile
    ;;
  list)
    cmd_list
    ;;
  login)
    cmd_login "$OBJECT"
    ;;
  replace)
    cmd_replace 
    ;;
  setup)
    cmd_setup
    ;;
  update)
    cmd_update
    ;;
  *)
    # echo $"Usage: $0 {start|stop|restart|condrestart|status}"
    usage
    exit 1
     
esac

#ansible-playbook \
#  ~/.ansible/collections/ansible_collections/tonykay/envy/playbooks/"${1}".yml \
#  -e "envy=${2}" # \
  # -e @~/.ansible/collections/ansible_collections/tonykay/envy/playbooks/vars/"${ENVIRONMENT}"/defauts

# 2> /tmp/warnings \
#  | tee /tmp/log | sed -n -e 's/.*ENVY_USER_OUTPUT//' -e 's/\"$//p'


