---

env_name: multi

envy_env_short_description: "multi: A simple multi-tier application infrastructure control, frontend, app1, app2, database"
envy_env_long_description: |
  "multi: A simple multi-tier application infrastructure control, frontend, app1, app2, database"


networks:
  default:
      name: example.com

services:

  control:
    container_name: control
    hostname: control
    image: tonykay/vmlet-rhel-8-ansible
    labels:
      com.envy.env_name: "{{ env_name }}"
    ports:
      - "22"
    privileged: true
      #volumes:
      #- "{{ envy_local_home }}/shared_dir/:/home/{{ envy_ssh_user }}/shared_dir:z,rw"

    
  frontend:
    container_name: frontend
    hostname: frontend
    image: tonykay/vmlet-rhel-8-ansible
    labels:
      com.envy.env_name: "{{ env_name }}"
    ports:
      - "22"
      - "8080:80"
    privileged: true

  app-01:
    container_name: app-01
    hostname: app-01
    image: tonykay/vmlet-rhel-8-ansible
    labels:
      com.envy.env_name: "{{ env_name }}"
    ports:
      - "22"
    privileged: true

  app-02:
    container_name: app-02
    hostname: app2
    image: tonykay/vmlet-rhel-8-ansible
    labels:
      com.envy.env_name: "{{ env_name }}"
    ports:
      - "22"
    privileged: true

  appdb:
    container_name: appdb
    hostname: appdb
    image: tonykay/vmlet-rhel-8-ansible
    labels:
      com.envy.env_name: "{{ env_name }}"
    ports:
      - "22"
    privileged: true
...
