---

- name: Manage container network(s)
  community.docker.docker_network:
    name:             "{{ __network.name }}"
    state:            "{{ envy_state | default('present') }}"
    labels:           "{{ envy_labels }}"
  loop: "{{ envy_networks }}"
  loop_control:
    loop_var: __network
  become: "{{ 'no' if ansible_system == 'Darwin' else 'yes' }}"
  tags:
    - network
    - networking

...
