---
- name: Create lab docker network {{ docker_network }} with options
  docker_network:
    name: "{{ docker_network }}"
    driver_options:
      com.docker.network.bridge.name: "{{ docker_bridge_name }}"
    ipam_options:
      subnet: "{{ docker_subnet }}"
      gateway: "{{ docker_gateway }}"
...
