---

envy_home_location: "~"
envy_home_directory: "{{ envy_home_location }}/env-{{ envy_name }}"

envy_directories:
    - "{{ envy_home_directory }}"
    - "{{ envy_home_directory }}/utilities"
    # - "env-{{ envy_name }}/utilities"
    #    - "env-{{ envy_name }}/ssh"

envy_ansible_files:
  - file:         ansible.cfg
    directory:    ""
  - file:         ssh.cfg
    directory:    ""
    #    directory:    ssh
  - file:         docker_aliases.env
    directory:    utilities
#  - file:         ssh-jumpbox.cfg
#    directory:    ssh

...
