---

envy_addon_short_description: Tower - An empty RHEL instance `tower` for Ansible Tower deployment scenarios

services:
  tower:
    container_name: tower
    image: tonykay/vmlet-rhel-7-target
    labels:
      com.envy.env_name: multi
    ports:
    - '22'
    - '8081:80'
    privileged: true
