---

envy_name:                    bookbag

envy_networks:
  - name:                     "{{ envy_default_domain | default('example.com') }}"

envy_instances:

  - name: terminal
    group: terminal
    image: quay.io/openshifthomeroom/workshop-terminal:latest
    published_ports:
      - "10080:10080"

  - name: lab-webserver
    group: lab-webserver
    image: rhel-8-lab-webserver
    published_ports:
      - "81:80"

...
