---

envy_name:                    sparse-multi

envy_networks:
  - name:                     "{{ envy_default_domain | default('example.com') }}"
    #  - name:                     internal.com

    
envy_default_image:           vmlet-rhel7-target

envy_instances:

  - name: control
    group: control_node
    image: vmlet-rhel8-ansible
    volumes:
      - "{{ envy_local_home }}/shared_dir/:/home/{{ envy_ssh_user }}/shared_dir:z,rw"

  - name: frontend1
    group: load_balancers
    published_ports:
      - "80:80"

  - name: app1
    group: app_servers

  - name: app2
    group: app_servers

  - name: appdb1
    group: database_servers

...
