---

- name: Create env directory structure for Ansible files (optional)
  file:
    path:     "{{ __directory }}"
    state:    directory
    mode:     "0755"
  loop: "{{ envy_directories }}"
  loop_control:
    loop_var: __directory

- name: Generate lab static inventory file
  template:
    src:      lab_inventory.j2
    dest:     "{{ envy_home_directory }}/inventory"
    mode:     "0644"

- name: Ensure user ssh config files exists
  lineinfile:
    path: ~/.ssh/config
    create: true
    state: present
    mode: "0644"
    line: "Include envy-config"

#- name: Copy ssh key to lab/ssh default to vagrant
#  copy:
#    src:      "{{ env_ssh_private_key | default('vagrant.private') }}"
#    dest:     "env-{{ env_name }}/ssh/{{ env_ssh_private_key | default('vagrant.private') }}"
#    dest:     "{{ envy_home_directory }}/{{ env_ssh_private_key | default('vagrant.private') }}"
#    mode:     0400

- name: "Copy ssh key to user .ssh  default to vagrant"
  copy:
    src:      "{{ env_ssh_private_key | default('vagrant.private') }}"
    dest:     "~/.ssh/{{ env_ssh_private_key | default('vagrant.private') }}"
    mode:     0400

- name: Write ansible lab config files
  template:
    src:     "{{ __files.file }}.j2"
    dest:    "{{ envy_home_directory }}//{{ __files.file }}"
    mode:    "0644"
  loop:     "{{ envy_ansible_files }}"
  loop_control:
    loop_var: __files

- name: Create user ssh Include config file
#  when: ansible_system != "Linux"
  template:
    src:     ssh.cfg.j2
    dest:    ~/.ssh/envy-config
    mode:    "0644"
...
