---

- name: Create the envy diretory and ansible configuration files
  when: envy_state == "present"
  include_tasks: create_envy_configuration.yml

- name: Remove the envy diretory and ansible configuration files
  when: envy_state == "absent"
  include_tasks: remove_envy_configuration.yml

- name: "Manage {{ envy_user }} ssh configuration"
  include_tasks: ssh_setup.yml
  
- name: Manage /etc/hosts on container host systems
  when: ansible_system == "Linux"
  include_tasks: hosts_setup.yml

...
