
networks:
  default:
    name: example.com

services:
  jenkins:
    container_name: jenkins
    image: tonykay/vmlet-rhel-8-ansible
    labels:
      com.envy.env_name: "{{ env_name }}"
    ports:
    - '22'
    - "81:8080"
