---

envy_volumes:
  - jenkins

addon_instance:

  - name: jenkins
    group: jenkins
    image: jenkins
    published_ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - "jenkins:/var/jenkins_home"

        #combined_instances: "{{ envy_instances | union(addon_instance) }}"

...
