---
- name: Create a container based ssh based lab environment - e.g. for Ansible
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    envy_state: present

  vars_files:
    - "vars/{{ envy | default('null') }}/default.yml"

#  vars:
#    combined_instances: "{{ envy_instances | union(addon_instances | default([])) }}"

  tasks:

    - name: Create individual env instances
      import_role:
        name: tonykay.envy.envy_manage_networks
      vars:
        envy_state: present

    - name: Create individual env instances
      import_role:
        name: tonykay.envy.envy_manage_instances
      vars:
        envy_container_state: started

    - name: Generate in-memory inventory
      import_role:
        name: tonykay.envy.envy_manage_inventory

    - name: Create env directory structure and files
      import_role:
        name: tonykay.envy.envy_manage_host_envy_configuration
      vars:
        envy_state: present  
      tags:
        - host-config

...
