---

- name: Deploy envy configuration and addons
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    envy_state: present

  roles:

    - tonykay.envy.envy_manage_deployments
    - tonykay.envy.envy_manage_inventory
    - tonykay.envy.envy_manage_host_envy_configuration

#  tasks:
#
#    - name: Create env directory structure and files
#      import_role:
#        name: tonykay.envy.envy_manage_host_envy_configuration
#      vars:
#        envy_state: present
#      tags:
#        - host-config

