---
- name: Create a container based ssh based lab environment - e.g. for Ansible
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars_files:
    - "vars/{{ env | default('three_tier') }}.yml"  # Default, over-ride -e @blueprints/<foo>

  roles:

    - envy_manage_host_env_configuration
    - envy_manage_instances
    - envy_manage_inventory
    - envy_manage_networks

...
