---
- name: Create a container based ssh based lab environment - e.g. for Ansible
  hosts: localhost
  connection: local
  gather_facts: false
  vars:

    foo: app

    envy_instances:

      - name: control
        group: control_node
        published_ports:
          - '22'
          - '8080:8080'
          - '5432'

      - name: app
        group: apps
        # image: rhel7-ssh
        networks:
          - name: internal.com
        published_ports:
          - '22'
          - '5432'
          - '8081:8080'

      - name: appdb
        group: appdbs
        published_ports:
          - '22'

  tasks:

    - name: Output value of bar
      debug:
        msg: "{{ bar }}"

    - name: Output instances
      debug:
        msg:
          - Extracted item is
          - "{{ envy_instances | to_nice_json }}"

    - name: Placeholder
      debug:
        msg:
          - "{{ envy_instances | json_query(jmesquery) }}"
      vars:
        jmesquery: "[*]"

    - name: Placeholder
      debug:
        msg:
          - "{{ envy_instances | json_query(jmesquery) }}"
      vars:
        # jmesquery: "[*].name"
        # jmesquery: "[? name=='app']"
        jmesquery: "[? name=='{{ foo }}']"
