---

classroom_instances:

  - name: antora
    group: antora
    image: antora/antora
    cmd:
    volumes:
      - "{{ envy_local_home }}/.classroom/source:/antora:z,rw"

  - name: terminal
    group: terminal
    image: quay.io/openshifthomeroom/workshop-terminal:latest
    published_ports:
      - "10080:10080"

  - name: lab-webserver
    group: lab-webserver
    image: registry.access.redhat.com/rhel8/httpd-24
    volumes:
      - "{{ envy_local_home }}/.classroom/output:/antora:z,rw"
    published_ports:
      - "8888:80"

...
