---

envy_instances:

#  - name: antora
#    group: antora
#    image: antora/antora
#    cmd: classroom.yml 
#    volumes:
#      - "{{ envy_local_home }}/.classroom:/antora:z,rw"

  - name: terminal
    group: terminal
    image: quay.io/openshifthomeroom/workshop-terminal:latest
    published_ports:
      - "10080:10080"

  - name: docs
    group: docs
    image: quay.io/varodrig/containers-lab:1.0
    published_ports:
    - "8080:80"

#  - name: classroom
#    group: classroom-backend
#    image: rhel-8-httpd  
#    volumes:
#      - "{{ envy_local_home }}/.classroom/output:/var/www/html/:z,rw"
#      - "~/.ansible/collections/ansible_collections/tonykay/envy/playbooks/vars/classroom/index.html://var/www/html/index.html:z,rw"
#    published_ports:
#      - "80:8080"

  - name: classroom
    group: classroom
    image: httpd 
    volumes:
      - "/Users/tok/.ansible/collections/ansible_collections/tonykay/envy/playbooks/vars/classroom/index.html:/usr/local/apache2/htdocs/index.html:ro"
    published_ports:
      - "80:80"

#  - name: classroom
#    group: lab-webserver
#    image: "agnosticlpweb:1.0"
#    volumes:
#      - "/tmp/index.html:/usr/share/nginx/html/index.html:z,rw"
#    published_ports:
#      - "80:80"

...
